INCLUDE "MACROS.TXT"

DATA SEGMENT
    MESSAGE1 DB "DOSE 1H AKOLOUTHIA:",'$'
    MESSAGE2 DB "DOSE 2H AKOLOUTHIA:",'$'
    MESSAGE3 DB "OCT:",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK
                                   
PRINT_DEC PROC NEAR
    MOV BX,0
    MOV CX,0
LOOP1:
    SUB DX,2710H
    CMP DX,0
    JL  EXIT1
    INC BH
    JMP LOOP1
EXIT1:
    ADD BH,30H
    ADD DX,2710H
LOOP2:
    SUB DX,03E8H
    CMP DX,0
    JL  EXIT2
    INC BL
    JMP LOOP2
EXIT2:
    ADD BL,30H
    ADD DX,03E8H
LOOP3:
    SUB DX,64H
    CMP DX,0
    JL  EXIT3
    INC CH
    JMP LOOP3
EXIT3:     
    ADD CH,30H
    ADD DX,64H
LOOP4:
    SUB DX,0AH
    CMP DX,0
    JL  EXIT4
    INC CL
    JMP LOOP4
EXIT4:
    ADD CL,30H
    ADD DX,0AH
    ADD DX,30H
    CMP BH,30H
    JE  NOT_ALL
    PUSH DX
    PRINT BH
    POP DX
NOT_ALL:
    PUSH DX    
    PRINT BL
    PRINT CH
    PRINT CL
    POP DX
    PRINT DL
    RET
PRINT_DEC ENDP

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START:

    PRINT_STR MESSAGE1
    MOV BX,00
    MOV CX,00
ARXH:
    READ
    CMP AL,32H
    JE PRINT1
    CMP AL,34H
    JE PRINT1
    CMP AL,36H
    JE PRINT1
    CMP AL,38H
    JE PRINT1
    JMP ARXH
    
PRINT1:
    PRINT AL
    CMP AL,35H
    JNG OXIMEG
    INC BX
OXIMEG:
    INC CX
    CMP CX,01
    JNE D4001
    MOV DX,4000H
    OUT DX,AX
D4001:
    CMP CX,02
    JNE D4002
    MOV DX,4001H
    OUT DX,AX
D4002:
    CMP CX,03
    JNE D4003
    MOV DX,4002H
    OUT DX,AX
D4003:
    MOV DX,4003H
    OUT DX,AX
    CMP CX,04
    JE NEXT
    JNE ARXH
NEXT:
    MOV CX,00
    PRINT_STR NEWLINE
    PRINT_STR MESSAGE2
NEXT1:
    READ
    CMP AL,31H
    JE PRINT2
    CMP AL,33H
    JE PRINT2
    CMP AL,35H
    JE PRINT2
    CMP AL,37H
    JE PRINT2
    CMP AL,39H
    JE PRINT2
    JMP NEXT1
PRINT2:
    PRINT AL
    CMP AL,35H
    INC CX
    CMP CX,01
    JNE D4005
    MOV DX,4004H
    OUT DX,AX
D4005:
    CMP CX,02
    JNE D4006
    MOV DX,4005H
    OUT DX,AX
D4006:
    CMP CX,03
    JNE D4007 
    MOV DX,4006H
    OUT DX,AX
D4007:
    MOV DX,4007H
    OUT DX,AX
    CMP CX,04
    JE NEXT2
    JNE NEXT1
NEXT2:
    PRINT_STR NEWLINE
    ADD BL,30H
    PRINT BL
    PRINT_STR NEWLINE
    MOV CX,00
    MOV BX,00
    MOV DX,4000H
    IN AX,DX
    MOV BX,AX
    MOV DX,4004H
    IN AX,DX
    CMP BX,AX
    JNG NEXT3
    INC CX
NEXT3:
    MOV BX,00
    MOV DX,4001H
    IN AX,DX
    MOV BX,AX
    MOV DX,4005H
    IN AX,DX
    CMP BX,AX
    JNG NEXT4
    INC CX
NEXT4:
    MOV BX,00
    MOV DX,4002H
    IN AX,DX
    MOV BX,AX
    MOV DX,4006H
    IN AX,DX
    CMP BX,AX
    JNG NEXT5
    INC CX
NEXT5:
    MOV BX,00
    MOV DX,4003H
    IN AX,DX
    MOV BX,AX
    MOV DX,4007H
    IN AX,DX
    CMP BX,AX
    JNG NEXT6
    INC CX
NEXT6:
    ADD CL,30H
    PRINT CL
    PRINT_STR NEWLINE 
    MOV CX,00
    MOV DX,4000H
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    INC DX
    IN AX,DX
    MOV AH,00
    SUB AL,30H
    ADD CX,AX
    MOV DX,CX
    MOV DH,00H
    CALL PRINT_DEC
    PRINT_STR NEWLINE
    
    
       
    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN