INCLUDE "MACROS.TXT" 


DATA SEGMENT
    MESSAGE1 DB "SUM=",'$'
    MESSAGE2 DB "HEX_SUM=",'$'
    MESSAGE3 DB "OCT:",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK
PRINT_HEX_DIGIT PROC NEAR
    CMP AL,09H
    JG  LETTER
NUMBER:
    ADD AL,30H
    PRINT AL
    RET
LETTER:
    ADD AL,37H
    PRINT AL
    RET
PRINT_HEX_DIGIT ENDP

PRINT_HEX PROC NEAR
    MOV BX,CX
    AND CX,0F000H
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ROR CH,1
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,0F00H
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,00F0H
    ROR CL,1
    ROR CL,1
    ROR CL,1
    ROR CL,1          
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,000FH
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
	MOV CX,BX
    RET
PRINT_HEX ENDP    
 
PRINT_OCT PROC NEAR
    MOV BX,CX
    AND CX,07000H
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ADD CH,30H
    PRINT CH
    MOV CX,BX
    AND CX,0E00H
    ROR CH,1
    ADD CH,30H
    PRINT CH
    MOV CX,BX
    AND CX,01F0H
    ROL CX,1
    ROL CX,1          
    ADD CH,30H
    PRINT CH
    MOV CX,BX
    AND CX,0038H
    ROR CL,1
    ROR CL,1
    ROR CL,1
    ADD CL,30H
    PRINT CL
    MOV CX,BX
    AND CX,07H
    ADD CL,30H
    PRINT CL
    MOV CX,BX
    RET    
PRINT_OCT ENDP   
                                   
READ_OCT_DIGIT PROC NEAR
OCT_DIGIT:
    READ
    CMP AL,075
    JE ENDING
    CMP AL,30H
    JL  OCT_DIGIT
    CMP AL,37H
    JG  OCT_DIGIT
    PRINT AL
    SUB AL,30H
    RET
READ_OCT_DIGIT ENDP 

READ_N_DIGIT_OCT PROC NEAR
    MOV BX,0
N_DIGIT_OCT:
    MOV CL,3
    ROL BX,CL
    CALL READ_OCT_DIGIT
    ADD BL,AL
    DEC DL
    CMP DL,00H
    JG  N_DIGIT_OCT
    RET 
READ_N_DIGIT_OCT ENDP

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START:
    MOV DX,2
    CALL READ_N_DIGIT_OCT
    MOV DX,4000H
    MOV AX,BX
    OUT DX,AX
PLUS:    
    READ
    CMP AL,075
    JE ENDING
    CMP AL,043
    JE NEXT
    JMP PLUS
NEXT:
    PRINT AL
    MOV DX,2    
    CALL READ_N_DIGIT_OCT

ENTER:
    READ
    CMP AL,13
    JE SUM
    JMP ENTER
SUM:
    PRINT_STR NEWLINE
    PRINT_STR MESSAGE1
    MOV DX,4000H 
    IN AX,DX
    MOV CX,AX
    ADD CX,BX 
    CALL PRINT_OCT
    PRINT_STR NEWLINE
    PRINT_STR MESSAGE2
    CALL PRINT_HEX
    PRINT_STR NEWLINE
    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN