INCLUDE "MACROS.TXT"

DATA SEGMENT
    MESSAGE1 DB "ENTER TWO DECIMAL NUMBERS:",'$'
    MESSAGE2 DB "DIF=",'$'
    MESSAGE3 DB "SUM=",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK
                                   
; Fill with functions here

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START: 

PRINT_STR MESSAGE1

READ_DEC PROC NEAR
    MOV CH,2
    MOV BX,0
AGAIN:
    READ 
    CMP AL,30H
    JL  AGAIN
    CMP AL,39H
    JG  AGAIN
    PRINT AL
    SUB AL,30H
    ADD BL,AL
    MOV CL,AL
    DEC CH 
    CMP CH,1
    JL NEXT
    JMP AGAIN
READ_DEC ENDP

NEXT:
    READ
    CMP AL,13
    JE DIF
    JMP NEXT
DIF:
    PRINT_NEWLINE 
    PRINT_STR MESSAGE2
    SUB BL,CL 
    CMP BL,CL
    JL ARNIT
    SUB BL,CL  
    JMP SINEX

ARNIT:
    MOV AL,45
    PRINT AL
    MOV CH,CL
    MOV CL,BL
    MOV BL,CH
    SUB BL,CL
     
SINEX:
    MOV DL,BL        
    PRINT_HEX2 PROC NEAR

	CMP DL,9
	JLE ADDRA2
	ADD DL,37H
	JMP ADDRB2

ADDRA2:
	ADD DL,30H

ADDRB2:
	PUSH AX
	MOV AH,2
	INT 21H
	POP AX
    PRINT_HEX2 ENDP
  
SUM:
    ADD BL,CL
    ADD BL,CL
    PRINT_NEWLINE
    PRINT_STR MESSAGE3
    


PRINT_HEX PROC NEAR
    MOV CX,BX
    MOV BX,CX
    AND CX,0F000H
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ROR CH,1
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,0F00H
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,00F0H
    ROR CL,1
    ROR CL,1
    ROR CL,1
    ROR CL,1          
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,000FH
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
	MOV CX,BX
    
PRINT_HEX ENDP 

    PRINT_HEX_DIGIT PROC NEAR
    CMP AL,09H
    JG  LETTER
NUMBER:
    ADD AL,30H
    PRINT AL
    RET
LETTER:
    ADD AL,37H
    CMP AL,70
    JG NO
    PRINT AL
    NO:
PRINT_HEX_DIGIT ENDP 

    PRINT_NEWLINE
    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN