INCLUDE "MACROS.TXT"

DATA SEGMENT
    MESSAGE1 DB "DOSE TO STRING:",'$'
    MESSAGE2 DB "HEX:",'$'
    MESSAGE3 DB "OCT:",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK
                                   
PRINT_DEC PROC NEAR
    MOV BX,0
    MOV CX,0
LOOP1:
    SUB DX,2710H
    CMP DX,0
    JL  EXIT1
    INC BH
    JMP LOOP1
EXIT1:
    ADD BH,30H
    ADD DX,2710H
LOOP2:
    SUB DX,03E8H
    CMP DX,0
    JL  EXIT2
    INC BL
    JMP LOOP2
EXIT2:
    ADD BL,30H
    ADD DX,03E8H
LOOP3:
    SUB DX,64H
    CMP DX,0
    JL  EXIT3
    INC CH
    JMP LOOP3
EXIT3:     
    ADD CH,30H
    ADD DX,64H
LOOP4:
    SUB DX,0AH
    CMP DX,0
    JL  EXIT4
    INC CL
    JMP LOOP4
EXIT4:
    ADD CL,30H
    ADD DX,0AH
    ADD DX,30H
    CMP BH,30H
    JE  NOT_ALL
    PUSH DX
    PRINT BH
    POP DX
NOT_ALL:
    PUSH DX    
    PRINT BL
    PRINT CH
    PRINT CL
    POP DX
    PRINT DL
    RET
PRINT_DEC ENDP

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START:

    PRINT_STR MESSAGE1
    MOV DL,00
    MOV CX,00
READ1:
    READ
    INC DL
    CMP AL,0DH
    JE NEXT1
    CMP AL,30H
    JE ENDING
    CMP AL,41H
    JL READ1
    CMP AL,5AH
    JG READ1
    MOV AH,00
    ADD CX,AX
    SUB CX,40H
    CMP CX,256
    JL NOMODULO256
    SUB CX,256
NOMODULO256:
    PRINT AL
    CMP DL,01
    JE PRWTOS
    JNE NEXT2
PRWTOS:
    MOV BH,AL
NEXT2:
    MOV BL,AL
    JMP READ1
    
NEXT1:
    MOV AX,CX
    MOV DX,4000H
    OUT DX,AX
    PRINT_STR NEWLINE
    CMP BL,BH
    JL NEGATIVE
    JNL POSITIVE
NEGATIVE:
    PRINT 45
    SUB BH,BL
    MOV DL,BH
    MOV DH,00
    CALL PRINT_DEC
    PRINT_STR NEWLINE
    JMP NEXT3
POSITIVE:
    SUB BL,BH
    MOV DL,BL
    MOV DH,00
    CALL PRINT_DEC
    PRINT_STR NEWLINE
    JMP NEXT3

NEXT3:

    MOV DX,4000H
    IN AX,DX
    MOV DX,AX
    CALL PRINT_DEC
    PRINT_STR NEWLINE

    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN