INCLUDE "MACROS.TXT"

DATA SEGMENT
    MESSAGE1 DB "GIVE THE NUMBERS:",'$'
    MESSAGE2 DB "HEX:",'$'
    MESSAGE3 DB "OCT:",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK
                                   
PRINT_HEX_DIGIT PROC NEAR
    CMP AL,09H
    JG  LETTER
NUMBER:
    ADD AL,30H
    PRINT AL
    RET
LETTER:
    ADD AL,37H
    PRINT AL
    RET
PRINT_HEX_DIGIT ENDP

PRINT_HEX PROC NEAR
    MOV BX,CX
    AND CX,0F000H
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ROR CH,1
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,0F00H
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,00F0H
    ROR CL,1
    ROR CL,1
    ROR CL,1
    ROR CL,1          
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,000FH
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
	MOV CX,BX
    RET
PRINT_HEX ENDP

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START:

    PRINT_STR MESSAGE1
    MOV BX,00
    MOV DX,4000H
READ1:
    READ
    CMP AL,51H
    JE ENDING
    CMP AL,0DH
    JE NEXT
    CMP AL,30H
    JL READ1
    CMP AL,39H
    JG READ1
    INC BX
    MOV AH,00
    OUT DX,AX
    INC DX
    CMP BX,07
    JE NEXT
    JMP READ1
    
NEXT:
    MOV AX,BX
    MOV AH,00
    MOV DX,4009H
    OUT DX,AX
    MOV DX,4000H
    MOV CX,00
NEXT1:
    IN AX,DX
    MOV AH,00
    PRINT AL
    INC DX
    DEC BX
    INC CX
    CMP BX,00
    JE NEXT2
    JMP NEXT1
NEXT2: 
    PRINT_STR NEWLINE
    MOV DX,4000H
NEXT3:
    IN AX,DX
    MOV AH,00
    CMP AL,31H
    JE EKTUP
    CMP AL,33H
    JE EKTUP
    CMP AL,35H
    JE EKTUP
    CMP AL,37H
    JE EKTUP
    CMP AL,39H
    JE EKTUP
    INC DX
    DEC CX
    CMP CX,00
    JE KANEKTUP
    JMP NEXT3
EKTUP:
    INC BX
    INC DX
    DEC CX
    CMP CX,00
    JE KANEKTUP
    JMP NEXT3
KANEKTUP:
    MOV AX,BX
    ADD AX,30H
    PRINT AL
NEXT4:
    PRINT_STR NEWLINE
    
    MOV DX,4009H
    IN AX,DX
    MOV AH,00
    MOV BX,AX
    MOV DX,4000H
    MOV CX,00
NEXT5:
    IN AX,DX
    MOV AH,00
    CMP AL,31H
    JE PROSTH
    CMP AL,33H
    JE PROSTH
    CMP AL,35H
    JE PROSTH
    CMP AL,37H
    JE PROSTH
    CMP AL,39H
    JE PROSTH
    INC DX
    DEC BX
    CMP BX,00
    JE NEXT6 
    JMP NEXT5
PROSTH:
    MOV AH,00
    IN AX,DX
    MOV AH,00
    ADD AX,CX
    MOV CX,AX
    SUB CX,30H
    INC DX
    DEC BX
    CMP BX,00
    JE NEXT6
    JMP NEXT5
NEXT6:
    CALL PRINT_HEX
    PRINT_STR NEWLINE
    

    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN