INCLUDE "MACROS.TXT"

DATA SEGMENT
    MESSAGE1 DB "GIVE THE NUMBERS:",'$'
    MESSAGE2 DB "HEX:",'$'
    MESSAGE3 DB "OCT:",'$'
    NEWLINE  DB 0AH,0DH,'$'    
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA,SS:STACK 
    
    PRINT_HEX_DIGIT PROC NEAR
    CMP AL,09H
    JG  LETTER
NUMBER:
    ADD AL,30H
    PRINT AL
    RET
LETTER:
    ADD AL,37H
    PRINT AL
    RET
PRINT_HEX_DIGIT ENDP

PRINT_HEX PROC NEAR
    MOV BX,CX
    AND CX,0F000H
    ROR CH,1
    ROR CH,1
    ROR CH,1
    ROR CH,1
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,0F00H
    MOV AL,CH
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,00F0H
    ROR CL,1
    ROR CL,1
    ROR CL,1
    ROR CL,1          
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
    MOV CX,BX
    AND CX,000FH
    MOV AL,CL
    CALL PRINT_HEX_DIGIT
	MOV CX,BX
    RET
PRINT_HEX ENDP
                                   
PRINT_DEC PROC NEAR
    MOV BX,0
    MOV CX,0
LOOP1:
    SUB DX,2710H
    CMP DX,0
    JL  EXIT1
    INC BH
    JMP LOOP1
EXIT1:
    ADD BH,30H
    ADD DX,2710H
LOOP2:
    SUB DX,03E8H
    CMP DX,0
    JL  EXIT2
    INC BL
    JMP LOOP2
EXIT2:
    ADD BL,30H
    ADD DX,03E8H
LOOP3:
    SUB DX,64H
    CMP DX,0
    JL  EXIT3
    INC CH
    JMP LOOP3
EXIT3:     
    ADD CH,30H
    ADD DX,64H
LOOP4:
    SUB DX,0AH
    CMP DX,0
    JL  EXIT4
    INC CL
    JMP LOOP4
EXIT4:
    ADD CL,30H
    ADD DX,0AH
    ADD DX,30H
    CMP BH,30H
    JE  NOT_ALL
    PUSH DX
    PRINT BH
    POP DX
NOT_ALL:
    PUSH DX    
    PRINT BL
    PRINT CH
    PRINT CL
    POP DX
    PRINT DL
    RET
PRINT_DEC ENDP

MAIN PROC FAR
    MOV AX,DATA
    MOV DS,AX
START:

    PRINT_STR MESSAGE1
    MOV CX,00
    MOV DX,4000H
ARXH:
    READ
    CMP AL,0DH
    JE EKTUPWSE
    CMP AL,51H
    JE ENDING
    CMP AL,30H
    JL ARXH
    CMP AL,39H
    JG ARXH
    OUT DX,AX
    INC DX
    INC CX
    CMP CX,06
    JE EKTUPWSE
    JMP ARXH
    
EKTUPWSE:
    MOV BX,00
    MOV DX,4000H
LOOPA:
    IN AX,DX
    MOV AH,00
    INC DX
    DEC CX
    INC BX
    PRINT AL
    CMP CX,00
    JE NEXT
    JNE LOOPA
NEXT:
    PRINT_STR NEWLINE
    MOV DX,4000H
    MOV CX,00
LOOPA2:
    CMP BX,00
    JE NEXT2
    IN AX,DX
    MOV AH,00
    CMP AL,30H
    JE ARTIOS
    CMP AL,32H
    JE ARTIOS
    CMP AL,34H
    JE ARTIOS
    CMP AL,36H
    JE ARTIOS
    CMP AL,38H
    JE ARTIOS
    INC DX
    DEC BX
    JMP LOOPA2
ARTIOS:
    SUB AL,30H
    ADD CL,AL
    INC DX
    DEC BX
    JMP LOOPA2
NEXT2:
    CALL PRINT_HEX
    PRINT_STR NEWLINE
    MOV DX,CX
    CALL PRINT_DEC
    PRINT_STR NEWLINE
    
    

    JMP START
ENDING:
    EXIT     
    
CODE ENDS
END MAIN